title: "I'm Gopi Palaniappan"
#author: "Gopi Palaniappan"
copyright: "2020-{{ YEAR }}"
description: "I blog about art. robotics. ml. games."
profilePicture: "images/profile.jpg"
footer: "&copy; [Gopi Palaniappan](/) 2020 - 2021"


disqusURL: "https://yihui.org"
githubContentURL: "https://github.com/tags07/tags07-website/edit/main/content/english/"
twitterImage: "images/profile.jpg"
keywords: ""
favicon: "favicons/"
# example ["css/custom.css"]
customCss: []
# example ["js/custom.js"]
customJs: []
mainSections:
  - "post"
images:
  - "images/site-feature-image.png"
doNotLoadAnimations: false


# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat: "2/1/2006"
indexDateFormat: "2/1/2006"
listDateFormat: "2/1/2006"

# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
fullPostContent: true


highlightjsCDN: "//cdn.bootcss.com"
highlightjsLang:
  - r
  - yaml
  - tex
highlightjsTheme: github
highlightjsVersion: 9.12.0



simpleAnalytics: {}
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
math:
  enable: false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  use: katex     # options: "katex", "mathjax". default is "katex".


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
socialIcons:
  - icon: "fab fa-linkedin"
    title: "Linkedin"
    url: "https://www.linkedin.com/in/tags07/"
  - icon: "fab fa-github"
    title: "GitHub"
    url: "https://github.com/tags07/"
  - icon: "fab fa-instagram"
    title: "instagram"
    url: "https://www.instagram.com/tags07/"
  - icon: "fas fa-envelope"
    title: "e-mail"
    url: "mailto:gopi.pm@gmail.com"


logo:
  en:
    img: "/images/profile.jpg"
    url: "/"
    alt: "Gopi Palaniappan"
    tag: ""


author:
  en: "Gopi Palaniappan"

lang:
  edit:
    en: "Edit this page"
  license:
    en: "License"
  subscribe:
    en: "Subscribe"


